import { LeaderboardEntry, Notification, Prize, Submission, User } from './types';

export const currentUser: User = {
  id: '1',
  username: 'johndoe',
  displayName: 'John Doe',
  avatarUri: 'https://i.pravatar.cc/150?img=12',
  points: 2450,
  rank: 7,
  submissions: 18,
  shippingAddress: '123 Main St, Apt 4B, New York, NY 10001',
};

export const mockSubmissions: Submission[] = [
  {
    id: '1',
    imageUri: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400',
    description: 'Large pothole on Main Street causing traffic issues',
    category: 'Road Maintenance',
    status: 'completed',
    points: 150,
    submittedDate: new Date('2025-10-15'),
    department: 'Public Works Department',
    aiCategorized: true,
    statusHistory: [
      { status: 'submitted', date: new Date('2025-10-15') },
      { status: 'received', date: new Date('2025-10-16'), department: 'Public Works Department' },
      { status: 'in-progress', date: new Date('2025-10-18') },
      { status: 'completed', date: new Date('2025-10-25') },
    ],
  },
  {
    id: '2',
    imageUri: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=400',
    description: 'Broken street light at Park Avenue intersection',
    category: 'Street Lighting',
    status: 'in-progress',
    points: 100,
    submittedDate: new Date('2025-10-28'),
    department: 'Utilities Department',
    aiCategorized: true,
    statusHistory: [
      { status: 'submitted', date: new Date('2025-10-28') },
      { status: 'received', date: new Date('2025-10-29'), department: 'Utilities Department' },
      { status: 'in-progress', date: new Date('2025-11-01') },
    ],
  },
  {
    id: '3',
    imageUri: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    description: 'Graffiti on public building wall',
    category: 'Vandalism',
    status: 'received',
    points: 75,
    submittedDate: new Date('2025-11-02'),
    department: 'City Maintenance',
    aiCategorized: true,
    statusHistory: [
      { status: 'submitted', date: new Date('2025-11-02') },
      { status: 'received', date: new Date('2025-11-03'), department: 'City Maintenance' },
    ],
  },
  {
    id: '4',
    imageUri: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=400',
    description: 'Water leak from fire hydrant',
    category: 'Water Infrastructure',
    status: 'submitted',
    points: 125,
    submittedDate: new Date('2025-11-04'),
    aiCategorized: true,
    statusHistory: [
      { status: 'submitted', date: new Date('2025-11-04') },
    ],
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    id: '101',
    username: 'cityheroes2025',
    displayName: 'Sarah Martinez',
    avatarUri: 'https://i.pravatar.cc/150?img=1',
    points: 5240,
    rank: 1,
    submissions: 42,
  },
  {
    id: '102',
    username: 'fixitfrank',
    displayName: 'Frank Johnson',
    avatarUri: 'https://i.pravatar.cc/150?img=3',
    points: 4890,
    rank: 2,
    submissions: 38,
  },
  {
    id: '103',
    username: 'communitywatch',
    displayName: 'Emily Chen',
    avatarUri: 'https://i.pravatar.cc/150?img=5',
    points: 4120,
    rank: 3,
    submissions: 35,
  },
  {
    id: '104',
    username: 'streetpatrol',
    displayName: 'Michael Brown',
    avatarUri: 'https://i.pravatar.cc/150?img=7',
    points: 3650,
    rank: 4,
    submissions: 29,
  },
  {
    id: '105',
    username: 'infrastructurepro',
    displayName: 'Lisa Anderson',
    avatarUri: 'https://i.pravatar.cc/150?img=9',
    points: 3210,
    rank: 5,
    submissions: 26,
  },
  {
    id: '106',
    username: 'civicguardian',
    displayName: 'David Wilson',
    avatarUri: 'https://i.pravatar.cc/150?img=11',
    points: 2890,
    rank: 6,
    submissions: 22,
  },
  {
    id: '1',
    username: 'johndoe',
    displayName: 'John Doe (You)',
    avatarUri: 'https://i.pravatar.cc/150?img=12',
    points: 2450,
    rank: 7,
    submissions: 18,
  },
  {
    id: '107',
    username: 'reportmaster',
    displayName: 'Jessica Lee',
    avatarUri: 'https://i.pravatar.cc/150?img=13',
    points: 2180,
    rank: 8,
    submissions: 17,
  },
];

export const mockPrizes: Prize[] = [
  {
    id: 'p1',
    title: '$10 Amazon Gift Card',
    description: 'Redeem your points for a $10 Amazon gift card',
    imageUri: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400',
    pointCost: 1000,
    category: 'Gift Cards',
    available: true,
  },
  {
    id: 'p2',
    title: '$25 Amazon Gift Card',
    description: 'Redeem your points for a $25 Amazon gift card',
    imageUri: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400',
    pointCost: 2500,
    category: 'Gift Cards',
    available: true,
  },
  {
    id: 'p3',
    title: 'City Hall Tour',
    description: 'Exclusive tour of City Hall with the mayor',
    imageUri: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400',
    pointCost: 500,
    category: 'Experiences',
    available: true,
  },
  {
    id: 'p4',
    title: 'Community Hero T-Shirt',
    description: 'Official Community Hero branded t-shirt',
    imageUri: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    pointCost: 300,
    category: 'Merchandise',
    available: true,
  },
  {
    id: 'p5',
    title: '$50 Restaurant Voucher',
    description: 'Dine at any participating local restaurant',
    imageUri: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
    pointCost: 3500,
    category: 'Gift Cards',
    available: true,
  },
  {
    id: 'p6',
    title: 'Coffee Mug Set',
    description: 'Set of 2 premium ceramic mugs with city logo',
    imageUri: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400',
    pointCost: 200,
    category: 'Merchandise',
    available: true,
  },
  {
    id: 'p7',
    title: 'Public Transit Monthly Pass',
    description: 'One month unlimited public transit pass',
    imageUri: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=400',
    pointCost: 4000,
    category: 'Transit',
    available: true,
  },
  {
    id: 'p8',
    title: 'Community Park Picnic',
    description: 'Reserved picnic area for you and 10 friends',
    imageUri: 'https://images.unsplash.com/photo-1506368083636-6defb67639a7?w=400',
    pointCost: 800,
    category: 'Experiences',
    available: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    title: 'Complaint Received!',
    message: 'Your pothole report has been received by the Public Works Department',
    date: new Date('2025-11-03'),
    type: 'success',
    submissionId: '1',
  },
  {
    id: 'n2',
    title: 'Work Started',
    message: 'Repairs have begun on your reported street light issue',
    date: new Date('2025-11-01'),
    type: 'info',
    submissionId: '2',
  },
  {
    id: 'n3',
    title: 'Points Earned!',
    message: 'You earned 150 points for your completed submission',
    date: new Date('2025-10-25'),
    type: 'success',
  },
];
